name: cvuload
dependencies:
- flask=0.10.1=py27_1
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_0
- jpeg=8d=0
- libgfortran=1.0=0
- libpng=1.6.17=0
- markupsafe=0.23=py27_0
- numpy=1.9.3=py27_0
- openblas=0.2.14=3
- opencv=2.4.10=np19py27_1
- openssl=1.0.1k=1
- pip=7.1.2=py27_0
- python=2.7.10=1
- readline=6.2=2
- setuptools=18.3.2=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- werkzeug=0.10.4=py27_0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0

